pipeline:
  lint-charts:
    image: guangbo/chart-testing:v1.0.3
    commands:
      - git remote add anaxexp-catalog https://github.com/anaxexp/catalog
      - git fetch anaxexp-catalog master
      - chart_test.sh --config test/.testenv --no-install
